### ISSUE TITLE
base image has been deprecated

### ISSUE THREAD

**Issue by 0xmichalis** [Roasbeef/btcd-in-a-box#1]
See https://hub.docker.com/r/google/golang/

Also why not move this into the main btcd repo?

**Comment by csibbitt** [comment]
I noticed this deprecation while working on my own Dockerfile. I submitted this: https://github.com/Roasbeef/btcd-in-a-box/pull/2

If there is any interest in it from the btcd team I can take a crack merging this work into the main btcd repo using the build-in-container workflow suggested by https://hub.docker.com/_/golang/

**Comment by Roasbeef** [comment]
Fixed by #2.

Concerning integrating this `Dockerfile`, into `btcd`:  it may be worth investigating integrating a [Content Trust](https://blog.docker.com/2015/08/content-trust-docker-1-8/) framework for signing+verifying the official Docker images for `btcd`.

Closing.
