### ISSUE TITLE
Version confusion?

### ISSUE THREAD

**Issue by LordMike** [Roasbeef/btcd-in-a-box#3]
I ran `latest`, and I got a rather old `0.9.0-beta`.. Once I discovered this, I switched the tag `0.11.0-beta`, and surprisingly I got the latest `0.12.0-beta` - perhaps a proper tag is in order? :)

Otherwise good image - glad to have it.

**Comment by Richard87** [comment]
The latest pushed image is outdated, and won't be able to sync the blockchain.

The GoLang version needs to be updated, and the sourcecode...

**Comment by farukterzioglu** [comment]
@Richard87 What needs to be updated in source code, can you elaborate?
